# Generated by Django 2.0.6 on 2018-06-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_details', models.TextField()),
                ('score', models.IntegerField()),
                ('AA_number', models.IntegerField()),
                ('AA_matching_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mol_id', models.TextField()),
                ('path_to_mol', models.TextField()),
                ('extra_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_prediction', models.TextField()),
                ('genome_id', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='matchingresult',
            name='mol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Mol'),
        ),
        migrations.AddField(
            model_name='matchingresult',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Prediction'),
        ),
    ]
